[package]
name = "ya_bike_bot"
version = "0.1.0"
authors = ["Pedro Lopes de Azevedo <ordepi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2"
actix-rt = "1"
dotenv= "0.15.0"
reqwest = { version = "0.10", features = ["json"] }
